# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-rest-addons}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cyril Rohr"]
  s.date = %q{2009-11-13}
  s.description = %q{A set of helpers and extensions for sinatra apps that expose REST resources.}
  s.email = %q{cyril.rohr@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/sinatra/rest/helpers.rb",
     "lib/sinatra/rest/routes.rb",
     "test/helper.rb",
     "test/routes_test.rb"
  ]
  s.homepage = %q{http://github.com/crohr/sinatra-rest-addons}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A set of helpers and extensions for sinatra apps that expose REST resources.}
  s.test_files = [
    "test/helper.rb",
     "test/routes_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<contest>, [">= 0"])
    else
      s.add_dependency(%q<contest>, [">= 0"])
    end
  else
    s.add_dependency(%q<contest>, [">= 0"])
  end
end

